apiVersion: topic.kafka.crossplane.io/v1alpha1
kind: Topic
metadata:
  name: topic
spec:
  forProvider:
    replicationFactor: 1
    partitions: 13
    compressionType: "snappy"
    deleteRetentionMs: 86400000
    preallocate: false

  providerConfigRef:
    name: example
