apiVersion: topic.kafka.crossplane.io/v1alpha1
kind: Topic
metadata:
  name: topic
spec:
  forProvider:
    replicationFactor: 1
    partitions: 11
    compressionType: "snappy"
  providerConfigRef:
    name: example
