apiVersion: topic.kafka.crossplane.io/v1alpha1
kind: Topic
metadata:
  name: topic2
spec:
  forProvider:
    replicationFactor: 1
    partitions: 1
    config:
      compression.type: "snappy"
      delete.retention.ms: "86400000"
  providerConfigRef:
    name: example
