apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: bob
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: dev
spec:
  authentication:
    type: scram-sha-512
---
apiVersion: user.kafka.crossplane.io/v1alpha1
kind: User
metadata:
  name: cluster-sample-user-byop
  annotations:
    crossplane.io/external-name: bob
spec:
  managementPolicies:
    - Observe
  forProvider:
    mechanisms:
      - SCRAM-SHA-512
    passwordSecretRef:
      name: bob-password
      namespace: default
      key: password
  writeConnectionSecretToRef:
    name: bob-kafka-credentials
    namespace: default
  providerConfigRef:
    name: default
