apiVersion: user.kafka.m.crossplane.io/v1alpha1
kind: User
metadata:
  name: sample-user
  namespace: kafka-cluster
  annotations:
    crossplane.io/external-name: alice
spec:
  forProvider:
    mechanisms:
      - SCRAM-SHA-512
  writeConnectionSecretToRef:
    name: alice-kafka-credentials
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
