apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: michael
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: dev
spec:
  authentication:
    type: scram-sha-512
---
apiVersion: user.kafka.m.crossplane.io/v1alpha1
kind: User
metadata:
  name: cluster-sample-user-byop
  namespace: kafka-cluster
  annotations:
    crossplane.io/external-name: michael
spec:
  managementPolicies:
    - Observe
  forProvider:
    mechanisms:
      - SCRAM-SHA-512
    passwordSecretRef:
      name: michael
      namespace: kafka-cluster
      key: password
  writeConnectionSecretToRef:
    name: michael-kafka-credentials
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
