apiVersion: kafka.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
  namespace: kafka-cluster
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: kafka-cluster
      name: kafka-creds
      key: credentials