apiVersion: v1
kind: Secret
metadata:
  name: kafka-creds
  namespace: kafka-cluster
type: Opaque
stringData:
  credentials: |
    {
      "brokers": [
        "kafka-0.kafka-headless:9092",
        "kafka-1.kafka-headless:9092",
        "kafka-2.kafka-headless:9092"
      ],
      "sasl": {
        "mechanism": "SCRAM-SHA-512",
        "username": "user1",
        "password": "password123"
      }
    }
