package v1alpha1

// TopicParameters are the configurable fields of a Topic.
type TopicParameters struct {
	// ReplicationFactor defines the number of replicas the topic should have.
	// +kubebuilder:validation:Minimum:=1
	ReplicationFactor int `json:"replicationFactor"`
	// Partitions defines the number of partitions the topic should have.
	// +kubebuilder:validation:Minimum:=1
	Partitions int `json:"partitions"`
	// Config is an optional map of string key/ value pairs.
	// +optional
	Config map[string]*string `json:"config,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicParameters) DeepCopyInto(out *TopicParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicParameters.
func (in *TopicParameters) DeepCopy() *TopicParameters {
	if in == nil {
		return nil
	}
	out := new(TopicParameters)
	in.DeepCopyInto(out)
	return out
}