apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kafka
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/provider-kafka
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      provider-kafka is a Crossplane Provider that is used to manage Kafka resources.
    meta.crossplane.io/readme: |
      provider-kafka is a Crossplane Provider that is used to manage Kafka resources,
      such as Kafka Topics and Access Control Lists.
    auth.upbound.io/group: kafka.crossplane.io
