apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dev
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: dev
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    sizeLimit: 1Gi
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: dev
  namespace: kafka-cluster
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.1-IV1
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: nodeport
        configuration:
          bootstrap:
            nodePort: 30092
        tls: false
        authentication:
          type: scram-sha-512

      - name: tls
        port: 9093
        configuration:
          bootstrap:
            nodePort: 30093
        type: nodeport
        tls: true
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      allow.everyone.if.no.acl.found: false
      # Require SASL authentication - reject anonymous connections
      authorizer.class.name: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      # Close connections that fail authentication quickly
      connections.max.idle.ms: 60000
      # Force re-authentication periodically
      connections.max.reauth.ms: 300000
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: user
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: dev
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: cluster
        operations:
          - All
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: pre-existing
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: dev
spec:
  partitions: 1
  replicas: 1
---