name: Publish Provider Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version string to use while publishing the package (e.g. v1.0.0-alpha.1)"
        default: ""
        required: false
      cleanup-disk:
        description: Whether or not perform a disk cleanup in the runner
        default: true
        type: boolean
        required: false

jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Extract Go version from go.mod
        id: extract-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "version=${GO_VERSION}" | tee -a $GITHUB_OUTPUT

  publish-provider-package:
    needs: get-go-version
    uses: crossplane-contrib/provider-workflows/.github/workflows/publish-provider.yml@main
    with:
      cleanup-disk: ${{ inputs.cleanup-disk }}
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      repository: provider-kafka
      version: ${{ github.event.inputs.version }}
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
      XPKG_MIRROR_ACCESS_ID: ${{ secrets.XPKG_ACCESS_ID }}
      XPKG_MIRROR_TOKEN: ${{ secrets.XPKG_TOKEN }}

  add-extensions:
    needs:
      - get-go-version
      - publish-provider-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - name: Login to Upbound
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_TOKEN }}
      - name: Append extensions
        run: make xpkg.append VERSION=${{ inputs.version }}
    env:
      GO_REQUIRED_VERSION: ${{ needs.get-go-version.outputs.go-version }}
      XPKG_MIRROR_ACCESS_ID: ${{ secrets.XPKG_ACCESS_ID }}
      XPKG_MIRROR_TOKEN: ${{ secrets.XPKG_TOKEN }}
